### PR TITLE
fix version bug

### PR DESCRIPTION
**Pull request by LinXueyuanStdio**
I fix the bug when running `pip install -e .` at root dir.

### CODE REVIEW

**Review by rosewang2008 — CHANGES_REQUESTED** [review]
Great, thanks for the fixes! I don't think the tqdm or huggingface-hub versions need to be updated. Did the previous versions give issues?

**Comment by LinXueyuanStdio** [comment]
the error occurs with `datasets==2.0.0`
```
The conflict is caused by:
    language-modeling-via-stochastic-processes 0.1.dev0 depends on tqdm==4.46.1
    language-modeling-via-stochastic-processes 0.1.dev0 depends on tqdm
    datasets 2.0.0 depends on tqdm>=4.62.1
```
```
datasets 2.0.0 requires huggingface-hub<1.0.0,>=0.1.0, but you have huggingface-hub 0.0.8 which is incompatible.
```

**Comment by LinXueyuanStdio** [comment]
I have tested the changed code. It can run without errors.

**Comment by LinXueyuanStdio** [comment]
On the other hand, we should update the version of `datasets` if we cannot update the version of tqdm or huggingface-hub.
Please let me know the proper version of `datasets` that I should use.

**Comment by rosewang2008** [comment]
I think keeping the datasets version fixed, and downgrading the rest would be better. Once you make those changes, I'll merge! :) Apologies for the delay in response.

**Pull request merged**
